[package]
name = "rust-scraper"
version = "0.1.0"
edition = "2019"

[dependencies]
http = "0.1"
lambda_runtime = "*"
now_lambda = "*"
scraper = "*"
url = "*"
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
